In [1]:
%load_ext autoreload
%autoreload 2

import modified_convcode as mcc
from commpy import channelcoding as cc
import numpy as np
from commpy.utilities import dec2bitarray, bitarray2dec

SEED = 0
rng = np.random.default_rng(SEED)

hello


In [2]:
cc_gen = np.array([[7, 5]])
cc_M = np.array([2])
cc_trellis = cc.Trellis(cc_M, cc_gen, feedback=0)

print("cc_trellis")
print(f"Trellis is code type {cc_trellis.code_type} and rate {cc_trellis.k}/{cc_trellis.n}")
print("Output table")
display(cc_trellis.output_table)
print("Next State table")
display(cc_trellis.next_state_table)

cc_trellis
Trellis is code type default and rate 1/2
Output table


array([[0, 3],
       [3, 0],
       [2, 1],
       [1, 2]])

Next State table


array([[0, 2],
       [0, 2],
       [1, 3],
       [1, 3]])

In [3]:
mcc_gen = np.array([[1, 1, 1], [1, 0 , 1]])
mcc_trellis = mcc.ModifiedTrellis(mcc_gen)

print("mcc_trellis")
print(f"Trellis is code type {mcc_trellis.code_type} and rate {mcc_trellis.k}/{mcc_trellis.n}")
print("Output table")
display(mcc_trellis.output_table)
print("Next State table")
display(mcc_trellis.next_state_table)

mcc_trellis
Trellis is code type default and rate 1/2
Output table


array([[0, 3],
       [3, 0],
       [2, 1],
       [1, 2]])

Next State table


array([[0, 2],
       [0, 2],
       [1, 3],
       [1, 3]])

In [4]:
message_bits = np.array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])
message_bits

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [5]:
cc_out = cc.conv_encode(message_bits, cc_trellis)
cc_out

Enterted conv encode with k=1; n=2; total_memory=2; rate=0.5; code_type=default
Using termination term
Running term termination
Running default code type
number_inbit=102; inbits=[1 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1
 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0]; number_outbits=204
Do I ever reach this code????


array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1])

In [6]:
mcc_out = cc.conv_encode(message_bits, mcc_trellis)
mcc_out

Enterted conv encode with k=1; n=2; total_memory=2; rate=0.5; code_type=default
Using termination term
Running term termination
Running default code type
number_inbit=102; inbits=[1 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1
 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0]; number_outbits=204
Do I ever reach this code????


array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1])

In [7]:
np.all(mcc_out == cc_out)

True

In [8]:
message_bits.ndim

1

In [16]:
test_message_bits = np.array([1, 1, 0, 1, 0])
mcc_tst_out = mcc.modified_conv_encode(test_message_bits, mcc_trellis, shift=0, terminate=True)
cc_test_out = cc.conv_encode(test_message_bits, mcc_trellis)

[MCC] Modfied msg bits: [1 1 0 1 0 0 0]
[MCC] Num inbits 7
[MCC] Num outbits 14
[MCC] Time 0 current state 0
[MCC] Time 0 output val 3
[MCC] Time 1 current state 2
[MCC] Time 1 output val 1
[MCC] Time 2 current state 3
[MCC] Time 2 output val 1
[MCC] Time 3 current state 1
[MCC] Time 3 output val 0
[MCC] Time 4 current state 2
[MCC] Time 4 output val 2
[MCC] Time 5 current state 1
[MCC] Time 5 output val 3
[MCC] Time 6 current state 0
[MCC] Time 6 output val 0
Enterted conv encode with k=1; n=2; total_memory=2; rate=0.5; code_type=default
Using termination term
Running term termination
Running default code type
number_inbit=7; inbits=[1 1 0 1 0 0 0]; number_outbits=14
Do I ever reach this code????
[CC] Time 0 state 0
[CC] Time 0 output val 3
[CC] Time 1 state 2
[CC] Time 1 output val 1
[CC] Time 2 state 3
[CC] Time 2 output val 1
[CC] Time 3 state 1
[CC] Time 3 output val 0
[CC] Time 4 state 2
[CC] Time 4 output val 2
[CC] Time 5 state 1
[CC] Time 5 output val 3
[CC] Time 6 state 0
[CC

In [18]:
mcc_mce_out = mcc.modified_conv_encode(message_bits, mcc_trellis, terminate=True)
print("modfied conv encode out")
display(mcc_mce_out)
print("conv encode out")
display(cc_out)

[MCC] Modfied msg bits: [1 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1
 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0]
[MCC] Num inbits 102
[MCC] Num outbits 204
modfied conv encode out


array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1])

conv encode out


array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1])

In [19]:
np.all(mcc_mce_out == cc_out)
# print(len(mcc_mce_out))
# print()

True