In [2]:
%load_ext autoreload
%autoreload 2

from commpy import channelcoding as cc
import numpy as np
from commpy.utilities import dec2bitarray, bitarray2dec

SEED = 0
rng = np.random.default_rng(SEED)

hello


In [4]:
dec2bitarray(4, 3)

array([1, 0, 0], dtype=int8)

In [8]:
generator_matrix75 = np.array([[7, 5]])
feedback7 = 7
M = np.array([2])
block_len = 100
trellis757 = cc.Trellis(M, generator_matrix75 , feedback=feedback7)

# generator_matrix25 = np.array([[1, 5]])
# trellis25 = cc.Trellis(M, generator_matrix25)

interleaver = cc.RandInterlv(block_len, 0)

In [9]:
print("Trellis757")
print(f"Trellis is code type {trellis757.code_type} and rate {trellis757.k}/{trellis757.n}")
print("Output table")
display(trellis757.output_table)
print("Next State table")
display(trellis757.next_state_table)

Trellis757
Trellis is code type default and rate 1/2
Output table


array([[0, 3],
       [0, 3],
       [1, 2],
       [1, 2]])

Next State table


array([[0, 2],
       [2, 0],
       [3, 1],
       [1, 3]])

In [10]:
message_bits = np.array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])
message_bits

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [12]:
[sys, par1, par2] = cc.turbo_encode(message_bits, trellis757, trellis757, interleaver)
print("Systematic stream")
display(sys)
print(f"Systematic is same as message? {np.all(message_bits == sys)}")
display(par1)
display(par2)

encoding turbo code
Enterted conv encode with k=1; n=2; total_memory=2; rate=0.5; code_type=default
Using termination rsc
Running term termination
Running default code type
number_inbit=102; inbits=[1 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1
 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0]; number_outbits=204
Enterted conv encode with k=1; n=2; total_memory=2; rate=0.5; code_type=default
Using termination rsc
Running term termination
Running default code type
number_inbit=102; inbits=[0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 1 0 0 1 1 1 0 1 0 1 0 0 0 1
 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0
 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0]; number_outbits=204
Systematic stream


array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

Systematic is same as message? True


array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0])

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [1]:
puncture_matrix=np.array([[1, 0]])
display(cc.conv_encode(message_bits, trellis1, puncture_matrix=puncture_matrix))

cc.conv_encode(message_bits, trellis1)

NameError: name 'np' is not defined

In [ ]:
dec2bitarray