In [1]:
import tensorflow as tf

2021-12-31 11:19:39.431472: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-31 11:19:39.431491: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [7]:
class Test:
    
    def __init__(self):
        self.permutation = None
    
    def reset(self):
        print("resetting")
        self.permutation = None
    
    def __call__(self, msg):
        if self.permutation is None:
            print("permutation is not set")
            self.permutation = tf.random.shuffle(tf.range(100))
        return tf.gather(msg, self.permutation)

In [14]:
test = Test()

@tf.function
def f(msg):
    # test.reset()
    return test(msg), test(msg)

In [15]:
display(f(tf.range(100)))
display(test.permutation)
display(f(tf.range(100)))
display(test.permutation)
display(f(tf.range(100)))

permutation is not set


(<tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([75, 97, 84, 41, 40, 51, 70, 58, 28, 64, 57, 18, 14, 74, 31, 34, 89,
        19, 25, 35, 91, 68, 98, 76, 30, 66, 29, 26, 56, 27,  0, 73,  6, 86,
        79, 15, 96,  2, 55, 85, 45, 77, 38, 17, 20, 92, 59, 93,  9, 99,  7,
        54, 67, 43, 71, 22, 94, 42, 46, 24, 50, 80, 60, 21, 10, 65, 36, 72,
        52, 37, 63, 33, 95, 32, 82, 81, 53, 90,  5,  3, 69, 11, 49, 12, 39,
         1,  4, 88, 16, 13, 83, 23, 44, 61, 47,  8, 78, 48, 87, 62],
       dtype=int32)>,
 <tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([75, 97, 84, 41, 40, 51, 70, 58, 28, 64, 57, 18, 14, 74, 31, 34, 89,
        19, 25, 35, 91, 68, 98, 76, 30, 66, 29, 26, 56, 27,  0, 73,  6, 86,
        79, 15, 96,  2, 55, 85, 45, 77, 38, 17, 20, 92, 59, 93,  9, 99,  7,
        54, 67, 43, 71, 22, 94, 42, 46, 24, 50, 80, 60, 21, 10, 65, 36, 72,
        52, 37, 63, 33, 95, 32, 82, 81, 53, 90,  5,  3, 69, 11, 49, 12, 39,
         1,  4, 88, 16, 13, 83, 23, 44, 61, 47,  8, 78,

<tf.Tensor 'RandomShuffle:0' shape=(100,) dtype=int32>

(<tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([69, 79, 17, 11, 41, 68, 32, 84, 34, 16, 20, 91, 52, 76, 99, 92,  1,
        36, 58, 29, 63, 22, 96, 86, 55, 39, 37, 64, 46, 18, 30, 74, 28, 98,
        83, 72, 10, 23, 62, 44, 48, 70, 33, 75, 50, 21,  2, 81, 49, 47, 80,
        35,  7,  0, 59, 66, 12,  4, 14, 15, 73, 71, 51, 78, 88, 42, 38, 54,
        31, 57, 13,  9, 95, 85,  8, 53, 77, 27, 87, 65,  5, 40, 25, 24, 56,
        94, 60, 97, 43,  6,  3, 93, 82, 89, 19, 45, 90, 61, 67, 26],
       dtype=int32)>,
 <tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([69, 79, 17, 11, 41, 68, 32, 84, 34, 16, 20, 91, 52, 76, 99, 92,  1,
        36, 58, 29, 63, 22, 96, 86, 55, 39, 37, 64, 46, 18, 30, 74, 28, 98,
        83, 72, 10, 23, 62, 44, 48, 70, 33, 75, 50, 21,  2, 81, 49, 47, 80,
        35,  7,  0, 59, 66, 12,  4, 14, 15, 73, 71, 51, 78, 88, 42, 38, 54,
        31, 57, 13,  9, 95, 85,  8, 53, 77, 27, 87, 65,  5, 40, 25, 24, 56,
        94, 60, 97, 43,  6,  3, 93, 82, 89, 19, 45, 90,

<tf.Tensor 'RandomShuffle:0' shape=(100,) dtype=int32>

(<tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([69, 45, 68, 56, 23, 25, 13, 74, 91, 63, 31, 72, 33, 75,  9, 20, 54,
        73, 10, 86,  0, 79, 29, 50, 19, 77, 55, 51, 65, 81, 53,  5, 61, 24,
        26, 42, 35, 47, 16, 40, 18, 66, 59, 89, 52, 97, 80, 28, 46,  2, 14,
        90, 83, 60, 78, 76, 34, 27, 98, 41, 67, 99,  7,  3, 32, 93, 11, 96,
        87, 48, 84,  4, 70, 43, 62, 94, 88, 36, 82, 22, 95, 39, 71, 44, 85,
        17, 64, 21, 57, 37, 12, 30,  6, 15,  1,  8, 92, 49, 38, 58],
       dtype=int32)>,
 <tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([69, 45, 68, 56, 23, 25, 13, 74, 91, 63, 31, 72, 33, 75,  9, 20, 54,
        73, 10, 86,  0, 79, 29, 50, 19, 77, 55, 51, 65, 81, 53,  5, 61, 24,
        26, 42, 35, 47, 16, 40, 18, 66, 59, 89, 52, 97, 80, 28, 46,  2, 14,
        90, 83, 60, 78, 76, 34, 27, 98, 41, 67, 99,  7,  3, 32, 93, 11, 96,
        87, 48, 84,  4, 70, 43, 62, 94, 88, 36, 82, 22, 95, 39, 71, 44, 85,
        17, 64, 21, 57, 37, 12, 30,  6, 15,  1,  8, 92,

In [16]:
import tensorflow_probability as tfp

In [33]:
a = tfp.experimental.stats.RunningVariance.from_shape(shape=())
data1 = tf.ones((3,))
data2 = tf.ones((2,)) * 2
a.update(data1, axis=0).update(data2, axis=0).variance(ddof=1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.3>

In [31]:
a = tf.constant(1)
type(a.numpy())


numpy.int32

In [32]:
(3 * 1 + 2 * 2) / 5

1.4

In [2]:
logits = tf.reshape(tf.constant([1., -1., 0., 1., -1., 0.,]), (3, 2))
labels = tf.reshape(tf.constant([0., 0., 0., 1., 1., 1.]), (3, 2))
tf.nn.sigmoid_cross_entropy_with_logits(labels=labels, logits=logits)

2021-12-31 11:21:36.003655: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-31 11:21:36.004033: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-31 11:21:36.004079: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2021-12-31 11:21:36.004123: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2021-12-31 11:21:36.004165: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.3132617, 0.3132617],
       [0.6931472, 0.3132617],
       [1.3132617, 0.6931472]], dtype=float32)>